### ISSUE TITLE
provide an example image, or page?

### ISSUE THREAD

**Issue by arkarkark** [davatron5000/wobbly-box#1]
Its very strange that there is no example of this actually working either as a real example or an image either on the [blog post](https://daverupert.com/2024/01/wobblybox/) where you post about it, or somewhere in this repository. Could you add one please?

**Comment by immanuelfodor** [comment]
Here is it in JSFiddle, hit run multiple times to see the wobbliness: https://jsfiddle.net/gjv73nd0/

![image](https://github.com/davatron5000/wobbly-box/assets/21174107/6bd086f3-6dd9-4521-abf7-f3624c34034f)

![image](https://github.com/davatron5000/wobbly-box/assets/21174107/9a3d4f07-714e-4051-a437-e09ec7b5f9e0)

You can adjust the dent in the lines by changing the constants here:

```diff
-    this.blockWobble = Math.random() * 2 - 1;
-    this.inlineWobble = Math.random() * 2 - 1;
+    this.blockWobble = Math.random() * 5 - 1;
+    this.inlineWobble = Math.random() * 5 - 1;
```

![image](https://github.com/davatron5000/wobbly-box/assets/21174107/b910b579-77ca-4c6c-aa0f-aa44d6932c3a)

The [blog post](https://daverupert.com/2024/01/wobblybox/) actually contains a demo, refresh the page multiple times to see it change:

<img src="https://github.com/davatron5000/wobbly-box/assets/21174107/914aa542-6793-46d6-8693-6f39f29e4db3" width=400>

**Comment by arkarkark** [comment]
thanks!
